apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    version: 2
    jsonData:
      version: Flux
      organization: rivflux
      defaultBucket: rivian
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
